# list of grimy herbs
grimy_herbs = {
    "grimy guam": [1, 2.5],
    "grimy tarromin": [5, 3.8],
    "grimy marrentill": [9, 5.0],
    "grimy harralander": [20, 6.3],
    "grimy ranarr": [25, 7.5],
    "grimy toadflax": [30, 8.0],
    "grimy spirit weed": [35, 7.8],
    "grimy irit": [40, 8.8],
    "grimy wergali": [41, 9.5],
    "grimy avantoe": [48, 10],
    "grimy kwuarm": [54, 11.3],
    "grimy bloodweed": [57, 11.5],
    "grimy snapdragon": [59, 11.8],
    "grimy cadantine": [65, 12.5],
    "grimy lantadyme": [67, 13.1],
    "grimy dwarf weed": [70, 13.8],
    "grimy torstol": [75, 15],
    "grimy arbuck": [77, 13.5],
    "grimy fellstalk": [91, 16.8],
}

# list of clean herbs
clean_herbs = [
    "clean guam", "clean tarromin", "clean marrentill", "clean harralander",
    "clean ranarr", "clean toadflax", "clean spirit weed", "clean irit", "clean avantoe",
    "clean wergali", "clean avantoe", "clean kwuarm", "clean bloodweed",
    "clean snapdragon", "clean cadantine", "clean lantadyme", "clean dwarf weed",
    "clean torstol", "clean arbuck", "clean fellstalk", "clean snake weed",
]

# list of secondary ingredients
secondary = [
    "eye of newt", "redberries", "magic bead", "limpwurt root",
    "clean snake weed", "bear fur", "unicorn horn dust", "ashes",
    "clean marrentill", "swamp tar", "red spider's eggs", "garlic",
    "silver dust", "chocolate dust", "rubium", "toad's legs",
    "goat horn dust", "season sheep wool", "star flower", "gorak claw powder",
    "wimpy feather", "rabbit teeth", "yew roots", "zygomite fruit", "wine of zamorak",
    "soil", "magic roots", "wyvern bonemeal", "morchella mushroom", "myecelial webbing",
    "poison slime", "green charm", "crimson charm", "gold charm", "blue charm", "spark chitin",
    "beak snot",
]

# {"potion": {lvl, xp, clean herb, primary, secondary, tertiary, quaternary}}
normal_potion = {
    "attack potion": {1, 25.0, "clean guam", "eye of newt"},
    "ranging potion": {3, 30.0, "clean guam", "redberries"},
    "magic potion": {5, 35.0, "clean tarromin", "magic bead"},
    "strength potion": {7, 40.0, "clean tarromin", "limpwurt root"},
    "defence potion": {9, 45.0, "clean marrentill", "bear fuf"},
    "antipoison": {13, 50.0, "clean marrentill", "unicorn horn dust"},
    "guthix rest": {18, 59.5, "clean harralander", "clean marrentill"},
    "guam tar": {19, 30.0, "clean guam", "swamp tar"},
    "restore potion": {22, 62.5, "clean harralander", "red spiders' eggs"},
    "guthix balance": {22, 50.0, "restore postion (3)", "garlic", "silver dust"},
    "energy potion": {26, 67.5, "clean harralander", "chocolate dust"},
    "marrentill tar": {31, 42.5, "clean marrentill", "swamp tar"},
    "super fishing explosive": {31, 55.0, "clean guam", "rubium"},
    "agility potion": {34, 80.0, "clean toadflax", "toad's legs"},
    "combat potion": {36, 84.0, "clean harralander", "goat horn dust"},
    "prayer potion": {38, 87.5, "clean ranarr", "snape grass"},
    "tarromin tar": {39, 55, "clean tarromin", "swamp tar"},
    "summoning potion": {40, 92, "clean spirit weed", "cockatrice egg"},
    "crafting poition": {42, 95, "clean wergali", "frog spawn"},
    "divination potion": {43, 97.5, "clean spirit weed", "rabbit foot"},
    "harralander tar": {44, 72.5, "clean harralander", "swamp tar"},
    "super attack": {45, 100, "clean irit", "eye of newt"},
    "super antipoison": {48, 106.3, "clean irit", "unicorn horn dust"},
    "fishing potion": {50, 112.5, "clean avantoe", "snape grass"},
    "super energy": {52, 117.5, "clean avantoe", "mort myre fungus"},
    "hunter potion": {53, 120, "clean avantoe", "kebbit teeth dust"},
    "runecrafting potion": {54, 122.5, "clean wergali", "season sheep wool"},
    "super strength": {55, 125, "clean kwuarm", "limpwurt"},
    "cooking potion": {55, 125, "clean harralander", "swordfish"},
    "magic essence potion": {57, 130, "star flower", "gorak claw powder"},
    "luck potion": {57, 123.5, "clean bloodweed", "crushed dragonstone"},
    "fletching potion": {58, 132, "clean wergali", "wimpy feather"},
    "weapon poison": {60, 137.5, "clean kwuarm", "dragon scale dust"},
    "super restore": {63, 142.5, "clean snapdragon", "red spiders' eggs"},
    "super hunter": {64, 145, "hunter potion (3)", "rabbit teeth"},
    # "sanfew serum": {65, 160, "super restore (3)", "unicorn horn dust", "clean snake weed", "nail beast nails"}
    "camouflage potion": {65, 150, "clean bloodweed", "black salamander"},
    "super defence": {66, 150, "clean cadantine", "white berries"},
    "antipoison+": {68, 155, "clean toadflax", "yew roots"},
    "antifire": {69, 157.5, "clean lantadyme", "dragon scale dust"},
    "super divination": {70, 160, "divination potion (3)", "zygomite fruit"},
    "super ranging potion": {72, 162.5, "clean dwarf weed", "wine of zamorak"},
    "weapon poison+": {73, 165, "cactus spine", "red spiders' eggs"},
    "super runecrafting": {75, 170.0, "runecrafting potion (3)", "yak milk"},
    "super magic potion": {76, 172.5, "clean lantadyme", "potato cactus"},
    "invention potion": {77, 175, "clean snapdragon", "chinchompa residue"},
    "stamina potion": {77, 175, "super energy (3)", "clean arbuck"},
    "archaeology potion": {78, 175, "clean avantoe", "soil"},
    "zamorak brew": {78, 175, "clean torstol", "jangerberries"},
    "antipoison++": {79, 177.5, "clean irit", "magic roots"},
    "super cooking potion": {79, 177.5, "cooking potion (3)", "zygomite fruit"},
    "extreme hunter": {80, 180, "super hunter (3)", "bull horns"},
    "saradomin brew": {81, 180, "clean toadflax", "crushed nest"},
    "weapon poison++": {82, 190, "cave nightshade", "poison ivy berries"},
    "aggression potion": {82, 185, "clean bloodweed", "searing ashes"},
    "adrenaline potion": {84, 200, "super energy (3)", "papaya fruit"},
    "super antifire": {85, 210, "antifire (3)", "phoenix feather"},
    "super adrenaline potion": {87, 200, "adrenaline potion (3)", "adrenaline crystal"},
    "super invention": {87, 220, "invention potion (3)", "spider fangs"},
    "extreme attack": {88, 220, "super attack (3)", "clean avantoe"},
    "summoning renewal": {88, 220, "spirit weed", "tombshroom"},
    "extreme strength": {89, 230, "super strength (3)", "clean dwarf weed"},
    "extreme divination": {89, 230, "super divination (3)", "yak fruit"},
    "extreme defence": {90, 240, "super defence (3)", "clean lantadyme"},
    "extended super antifire": {90, 210, "super antifire (3)", "clean arbuck"},
    "extreme magic": {91, 250, "super magic potion (3)", "ground mud runes"},
    "extreme runecrafting": {91, 250, "super runecrafting (3)", "spider venom"},
    "extreme ranging": {92, 260, "super ranging (3)", "grenwall spikes"},
    "super saradomin brew": {93, 180, "saradomin brew (3)", "wine of saradomin"},
    "super zamorak brew": {93, 180, "zamorak brew (3)", "wine of zamorak"},
    "super guthix rest": {93, 59.5, "guthix rest (3)", "wine of guthix"},
    "super prayer": {94, 270, "prayer potion (3)", "wyvern bonemeal"},
    "prayer renewal": {94, 190, "clean fellstalk", "morchella mushroom"},
    "extreme invention": {95, 300, "super invention (3)" "myecelial webbing"},
    "harvest potion": {95, 300, "primal extract", "clean arbuck", "watermelon"},
    "overload": {96, 1000, "extreme attack (3)", "extreme strength (3)",
                 "extreme defence (3)", "extreme magic (3)", "extreme ranging (3)",
                 "clean torstol"},
    "weapon poison+++": {100, 700, "weapon poison++ (3)", "poison slime", "primal extract"},
    "charming potion": {102, 1000, "primal extract", 4 * "gold charm", 4 * "green charm",
                        4 * "crimson charm", 4 * "blue charm", "spark chitin"},
    "extreme cooking potion": {104, 800, "super cooking potion (3)", "primal extract",
                               "beak snot"},
    "spirit attraction potion": {116, 1100, "primal fruit pulp", "enhanced luck potion",
                                 "timeworn tincture"},
    "extreme prayer": {117, 1200, "super prayer (3)", "primal extract", "spark chitin"}
}
